flowchart LR

subgraph 0["src"]
subgraph 1["core"]
subgraph 2["actions"]
3["base-action.ts"]
9["create.ts"]
A["operation.types.ts"]
B["delete.ts"]
C["get-many.ts"]
H["get-one.ts"]
I["index.ts"]
J["replace.ts"]
K["update.ts"]
end
4["adapter-api.ts"]
5["hook-context.ts"]
subgraph 6["utils"]
7["error-handler.ts"]
D["query-builder.ts"]
E["embed-builder.ts"]
F["filter-builder.ts"]
G["query-parser.ts"]
M["schema-inspector.ts"]
R["primary-key-utils.ts"]
S["schema-inspector.test.ts"]
end
8["logger.ts"]
L["adapter.ts"]
subgraph N["types"]
O["adapter.types.ts"]
P["handler.types.ts"]
Q["query.types.ts"]
end
end
end
subgraph T["@"]
subgraph U["db"]
V["schema"]
end
end
3-->4
3-->5
3-->7
7-->4
7-->8
9-->3
9-->A
B-->3
B-->A
C-->D
C-->G
C-->3
C-->A
D-->E
D-->F
H-->3
H-->A
I-->9
I-->B
I-->C
I-->H
I-->J
I-->K
J-->3
J-->A
K-->3
K-->A
L-->I
L-->A
L-->8
L-->7
L-->M
S-->M
S-->V
