flowchart LR

subgraph 0["src"]
subgraph 1["core"]
subgraph 2["actions"]
3["action.types.ts"]
4["base-action.ts"]
A["create.ts"]
B["delete.ts"]
C["get-many.ts"]
H["get-one.ts"]
I["index.ts"]
J["replace.ts"]
K["update.ts"]
end
5["adapter-api.ts"]
6["hook-context.ts"]
subgraph 7["utils"]
8["error-handler.ts"]
D["query-builder.ts"]
E["embed-builder.ts"]
F["filter-builder.ts"]
G["query-parser.ts"]
M["schema-inspector.ts"]
R["schema-inspector.test.ts"]
end
9["logger.ts"]
L["adapter.ts"]
subgraph N["types"]
O["adapter.types.ts"]
P["handler.types.ts"]
Q["query.types.ts"]
end
end
end
subgraph S["@"]
subgraph T["db"]
U["schema"]
end
end
4-->5
4-->6
4-->8
8-->5
8-->9
A-->3
A-->4
B-->3
B-->4
C-->D
C-->G
C-->3
C-->4
D-->E
D-->F
H-->3
H-->4
I-->3
I-->A
I-->B
I-->C
I-->H
I-->J
I-->K
J-->3
J-->4
K-->3
K-->4
L-->I
L-->3
L-->9
L-->8
L-->M
R-->M
R-->U
